/* Version: #5 */
// === CONFIGURATION ===
// Dette er databasen for unnskyldninger.
// Inneholder bidrag fra HV-soldater og AI-genererte forslag.

console.log("Starter lasting av excuses.js (Versjon 5)...");

const militaryExcuses = [
    // --- SAMBAND & TEKNISK (Orginal Startpakke) ---
    "Sambandet har null dekning i dette dalføret, helt dødt.",
    "Glemte krypteringsnøkkelen i den andre buksa.",
    "Tom for batteri på radioen, og reserven lå igjen på kaserna.",
    "Vi fikk inn russisk folkemusikk på nettet og ble distrahert.",
    "Antennen knakk da vi kjørte under en lav grein.",
    "GPS-jamming fra ukjent hold, vi navigerer etter sola.",
    "TS-nøkkelen knakk i låsen.",

    // --- Logistikk og Materiell (Fra bruker) ---
    "Venter på rekvisisjon av tørre sokker fra 1982.",
    "Har ikke fått utlevert motivasjon for denne øvelsen.",
    "Pussekluten er sendt til teknisk ettersyn.",
    "Logistikken har forvekslet kaffebønner med tennstempler.",
    "Venter på at S-4 skal godkjenne bruk av sivil binders.",
    "Feltstøvlene har gått i 'sivil streik'.",
    "Bukseselene mine er ikke lenger NATO-kompatible.",
    "Har mistet en splint i en høyball.",
    "Venter på leveranse av 'taktisk tålmodighet'.",
    "Uniformen min er for øyeblikket i en 'eksistensiell vaskeprosess'.",
    "Verktøysettet inneholdt bare to teskjeer og en binders.",
    "Har fått utlevert venstrehansker i størrelse XXL (bruker Small).",
    "Lageret er tomt for alt annet enn optimisme.",
    "Rekvisisjonen ble spist av en forvirret elg.",
    "Venter på at batteriene til kaffetrakteren skal lades.",
    "Har ikke fått godkjent bruk av lisser i feltstøvlene.",
    "Mangler signatur fra en offiser som gikk av med pensjon i fjor.",
    "PBU-en min er i 'taktisk dvale'.",
    "Er i kø for å bytte en teltplugg mot en pose Walters Mandler.",
    "Logistikksystemet tror jeg er en stridsvogn.",

    // --- Operasjoner og Taktikk (Fra bruker) ---
    "Gjennomfører en strategisk pause for å finne nord.",
    "Er i ferd med å etablere en fremskutt kaffepost.",
    "Utfører 'skjul og dekning' i kantina.",
    "Har gått i ett med terrenget (og glemt hvor jeg er).",
    "Venter på klarsignal fra en fugl som ser mistenkelig ut.",
    "Planlegger en taktisk omgåelse av oppvasken.",
    "Er i 'beredskapsklasse: kaffe og vaffel'.",
    "Har observert fienden, men de så så hyggelige ut.",
    "Utfører en flanke-manøver mot nærmeste bensinstasjon.",
    "Venter på at kartet skal oppdatere seg til 2026-standard.",
    "Er i en 'oppdragskritisk hvilefase'.",
    "Har forvekslet 'fremrykk' med 'tilbaketrekning til senga'.",
    "Venter på at tåka skal bli 'litt mer taktisk'.",
    "Sjekker om gresset faktisk er grønnere på andre siden av sperringen.",
    "Er i ferd med å reise et telt, men tyngdekraften samarbeider ikke.",
    "Har mistet kontakten med min indre kompassnål.",
    "Gjennomfører en 'lydløs forflytning' mot nærmeste kiosk.",
    "Er på en hemmelig misjon for å finne en stikkontakt.",
    "Venter på at ordren skal bli oversatt fra 'militærspråk' til 'norsk'.",
    "Er i en tilstand av 'kontrollert forvirring'.",

    // --- Samband og Teknikk (Fra bruker) ---
    "Sambandet er nede fordi noen snublet i en usynlig kabel.",
    "Batteriene på radioen er i 'vintermodus' (de døde umiddelbart).",
    "Får bare inn svensktopper på kryptert kanal.",
    "Antennen nektet å reise seg uten skriftlig samtykke.",
    "Radioen min snakker bare flytende finsk i dag.",
    "Venter på at IT-avdelingen skal 'godkjenne' naturen.",
    "GPS-en viser at jeg er midt i Atlanterhavet.",
    "Har fått 'blått lys' på felttelefonen.",
    "Sambandskoden er glemt, men jeg husker Netflix-passordet mitt.",
    "Har mistet kontakten med satellitten på grunn av en uvanlig lav sky.",
    "Laderen min ble byttet mot en pakke tørre kjeks.",
    "Tastaturet på laptopen har gått i 'feltmodus'.",
    "Er i en 'digital dødssone' rett ved siden av ruteren.",
    "Venter på en programvareoppdatering som krever 5G i skogen.",
    "Radioen piper hver gang jeg tenker på mat.",
    "Krypteringsnøkkelen ble vasket på 60 grader.",
    "Har forvekslet sambandsantenna med en fiskestang.",
    "Lyden på headsettet er erstattet av en konstant plystrelyd.",
    "Prøver å koble radioen til en kaffetrakter for mer kraft.",
    "Error 404: Motivation not found i displayet.",

    // --- Personell og Velferd (Fra bruker) ---
    "Har fått 'allergisk reaksjon' mot tidlige morgener.",
    "Venter på at moralen skal stige over frysepunktet.",
    "Er opptatt med å telle støv i løpet av børsa.",
    "Har fått innvilget 'mental permisjon' av meg selv.",
    "Er i kø for å klage på at kaffen er for våt.",
    "Venter på at sivil status skal overta for militær plikt.",
    "Har fått et akutt anfall av 'jeg-vil-hjem-syndromet'.",
    "Prøver å forklare hunden min at jeg er på øvelse.",
    "Er opptatt med å pusse medaljer jeg ennå ikke har fått.",
    "Venter på at håret mitt skal gro ut til godkjent lengde.",
    "Har glemt hvordan man går i takt uten musikk.",
    "Er i en dyp diskusjon med en furu om meningen med livet.",
    "Har fått gnagsår på sjelen.",
    "Venter på at noen skal si 'vel utført' før jeg starter.",
    "Er i ferd med å skrive en klage på at regnet faller vertikalt.",
    "Har mistet evnen til å sove uten en stein under ryggen.",
    "Prøver å finne ut hvem som har stjålet det siste smilet mitt.",
    "Er i 'hvilemodus' for å spare på sivil sjarm.",
    "Venter på at sersjanten skal si noe morsomt.",
    "Har fått forbud mot å tenke selv frem til lunsj.",

    // --- Heimeverns-spesial (Fra bruker) ---
    "Måtte hjelpe en nabo med å starte en traktor.",
    "Er 'litt her og der', mest 'der'.",
    "Trodde det var 'av og til', og i dag er det definitivt 'ikke nå'.",
    "Kona sa jeg måtte klippe gresset før jeg kunne redde landet.",
    "Har glemt hvilken lomme jeg la nøklene til HV-området i.",
    "Sivil sektor krever min tilstedeværelse ved kaffemaskinen.",
    "Har forvekslet feltflaska med en termos med kakao.",
    "Prøver å finne ut om HK416 passer i bagasjerommet på en Tesla.",
    "Er på utkikk etter en fiende som respekterer arbeidstiden.",
    "Venter på at elgjakta skal bli ferdig så vi får fred i skogen.",
    "Har fått melding om at traktoren står i veien for stridsvogna.",
    "Er i ferd med å mobilisere min egen tålmodighet.",
    "Har glemt om jeg er sivilist eller soldat akkurat nå.",
    "Venter på at posten skal levere nytt mot.",
    "Er opptatt med å forklare sjefen hvorfor jeg er i skogen.",
    "Har funnet ut at 'taktisk hvile' fungerer best i en god stol.",
    "Er 'av og til' flink, i dag er jeg bare 'av'.",
    "Prøver å kamuflere bilen min som en bringebærbusk.",
    "Venter på skriftlig ordre fra kona.",
    "Har gått tom for HV-humor.",

    // --- Blandet drops (Fra bruker) ---
    "Tåka er for tykk for min rang.",
    "Har fått ordre om å ikke gjøre noe, og jeg følger den til punkt og prikke.",
    "Venter på at sola skal gå ned så jeg kan bruke nattoptikken.",
    "Sjekker om støvlene mine er vanntette fra innsiden.",
    "Er i en taktisk diskusjon med en maurtue.",
    "Har mistet troen på kartlesing.",
    "Venter på at teltlaget skal bli enige om hvem som snorker mest.",
    "Er opptatt med å finne den perfekte sitte-steinen.",
    "Har fått 'felt-fatigue' etter 20 minutter.",
    "Prøver å lade telefonen med en primus.",
    "Venter på at snøen skal smelte så jeg finner magasinet mitt.",
    "Har fått beskjed om at 'vente på nærmere ordre' er dagens oppdrag.",
    "Er i ferd med å miste besinnelsen, finner ikke rekvisisjonen.",
    "Prøver å se ut som jeg vet hva jeg gjør.",
    "Venter på at kaffekjelen skal si 'klart til strid'.",
    "Er utilgjengelig på grunn av dårlig humør.",
    "Har forvekslet kamuflasjekrem med sjokoladepålegg.",
    "Venter på at noen andre skal ta initiativet.",
    "Er opptatt med å vurdere om regnet er fiendtlig.",
    "Har glemt passordet til teltåpningen.",
    "Venter på at logistikken skal levere varmere vær.",
    "Er i ferd med å etablere en 'ly-sone' bak en busk.",
    "Har fått ordre om å være usynlig, ingen har sett meg siden.",
    "Prøver å finne ut om det er lov å bruke paraply i uniform.",
    "Venter på at sersjanten skal gå tom for energi.",
    "Er opptatt med å skrive 'HV' med kvister i skogen.",
    "Har fått gnagsår på tålmodigheten.",
    "Venter på at feltrasjonen skal smake som biff.",
    "Er i en dyp dvale for å spare på statens ressurser.",
    "Prøver å finne ut hvorfor kartet er opp-ned.",
    "Venter på at naturen skal slutte å støye.",
    "Er opptatt med å telle kalorier i en tørr kjeks.",
    "Har fått melding om at kaffen er forsinket.",
    "Prøver å kamuflere meg som en sivilist.",
    "Venter på at vinden skal snu så jeg lukter lunsjen.",
    "Er i ferd med å gå tom for unnskyldninger.",
    "Har glemt hvilken vei som er frem.",
    "Venter på at moralen skal bli levert med helikopter.",
    "Er opptatt med å sjekke om hjelmen passer som suppebolle.",
    "Har fått forbud mot å bruke logikk i felt.",
    "Venter på at noen skal si 'det var bare en spøk'.",
    "Er i en taktisk venteposisjon (ligger i lyngen).",
    "Prøver å lade opp selvtilliten med en vaffel.",
    "Har forvekslet stridsropet med et gjesp.",
    "Venter på at utstyret skal fungere som i brosjyren.",
    "Er opptatt med å finne ut hvem som eier skogen.",
    "Har fått akutt behov for siviliserte tilstander.",
    "Venter på at noen skal forklare meg oppdraget sakte.",
    "Er i ferd med å miste kontakten med virkeligheten.",
    "Prøver å finne en unnskyldning som ikke er i denne appen.",
    "Venter på at skoene skal gå seg selv.",
    "Er opptatt med å se travel ut med et kart.",
    "Har fått melding om at fienden har tatt kaffepause.",
    "Venter på at batteriet på klokka skal dø.",
    "Er i ferd med å bli en del av det lokale økosystemet.",
    "Prøver å finne ut hvem som har slått av varmen i skogen.",
    "Har glemt hvordan man bruker en skje.",
    "Venter på at noen skal bære sekken min.",
    "Er opptatt med å unngå blikkontakt med befalet.",
    "Har fått ordre om å vente, jeg er en lojal soldat.",
    "Venter på at regnet skal bli til snø.",
    "Er i en tilstand av 'permanent beredskap for middag'.",
    "Prøver å tyde røyksignalene fra kjøkkenvogna.",
    "Har forvekslet vernebrillene med solbriller.",
    "Venter på at sivilisasjonen skal innhente oss.",
    "Er opptatt med å pusse støvlene med mose.",
    "Har fått beskjed om at alt er 'under kontroll'.",
    "Venter på at lyngen skal bli mykere.",
    "Er i ferd med å lære meg å snakke med rådyr.",
    "Prøver å finne ut om det er Wifi i skyttergrava.",
    "Har glemt hvorfor jeg sa ja til dette.",
    "Venter på at noen skal gi meg en medalje for oppmøte.",
    "Er opptatt med å vurdere om teltet er arkitektonisk forsvarlig.",
    "Alle unnskyldninger må godkjennes av S-1.",
    "Venter på at dagen skal bli 'litt mer sivil'.",
    "Er i ferd med å utvikle usynlig arbeid-kamuflasje.",
    "Prøver å finne ut om kaffen er NATO-standard.",
    "Har forvekslet øvelsen med en campingtur.",
    "Venter på at noen skal fortelle meg hvor jeg skal stå.",
    "Er opptatt med å unngå å bli 'frivillig'.",
    "Venter på at snøen skal slutte å være kald.",
    "Er i en taktisk pause for å sjekke appen.",
    "Prøver å finne ut hvem som har flyttet på horisonten.",
    "Har glemt hvordan man snakker uten å rope.",
    "Venter på at noen skal bære ansvaret.",
    "Er opptatt med å se på at gresset gror.",
    "Har fått beskjed om at 'snart' betyr fire timer.",
    "Venter på at tålmodigheten skal bli levert.",
    "Er i ferd med å bli ekspert på å vente.",
    "Prøver å finne en vei ut av denne lista.",
    "Venter på at sersjanten skal gå i pensjon.",
    "Er opptatt med å finne en unnskyldning for pause.",
    "Har forvekslet målet med en luftspeiling.",
    "Venter på at noen skal servere meg kaffe på post.",
    "Er i en tilstand av 'kontrollert kaos'.",
    "Prøver å finne ut om det er lov å sove med åpne øyne.",
    "Har glemt alt jeg lærte på rekruttskolen i 1998.",
    "Venter på at appen skal gi meg en bedre unnskyldning.",
    "Er opptatt med å være 'litt her og der'.",

    // --- NYTT PÅFYLL (AI Generert) ---
    // Nødnett & Samband
    "Nødnettet har tatt ferie, bruker røyksignaler.",
    "Frekvensen er opptatt av en taxisentral i Riga.",
    "Mikrofonen frøs fast til leppa.",
    "Har feil impedans i øret.",
    "Sambandslaget sa 'hallo', jeg svarte 'hade'.",

    // Feltliv & Boforhold
    "Soveposen min har utviklet klaustrofobi.",
    "Teltovnen nekter å brenne annet enn primus-instruksjoner.",
    "Har mistet liggeunderlaget, sover på ren viljestyrke.",
    "Knappeteltet ble montert som moderne kunst.",
    "Venter på at vannet i flaska skal tine (det er juli).",

    // Våpen & Utrustning
    "Magasinet sitter fast i taska pga. gammel sjokolade.",
    "Våpenolja har stivnet til sirup.",
    "Har pussa i stykker sluttstykket.",
    "Siktet er innstilt på 'fredstid'.",
    "Mangler vital del til AG-3 (som jeg lånte i 1999).",

    // Kjøretøy & Transport
    "Larveføttene på vogna har fått gnagsår.",
    "MB-en står fast i en sølepytt på størrelse med Mjøsa.",
    "Sjåføren er i ferd med å lese kartet opp-ned.",
    "Vi venter på deler fra et museum.",
    "Kjettingene er knyttet i knute.",

    // Ledelse & Kommando
    "Har fått ordre om å iverksette hvile, nekter å bryte ordre.",
    "Troppssjef leter etter kompasset sitt (vi tør ikke si noe).",
    "Avventer kontra-kontrabeskjed.",
    "Har søkt om fritak på grunn av akutt kaffetørst.",
    "NK har bestemt at vi skal snu døgnet.",

    // Helse & Hygiene
    "Har fått 'feltskjegg' som klør for mye til å skyte.",
    "Venter på at våtserviettene skal tørke.",
    "Har fått mose i øregangen.",
    "Er midlertidig blind på grunn av skarpt sollys (klokka er 02:00).",
    "Har utviklet allergi mot kommandoord.",

    // Vær & Vind
    "Motvinden er for sterk til å rykke frem.",
    "Regnet treffer meg vannrett i ansiktet uansett hvilken vei jeg står.",
    "Venter på at myggen skal gå og legge seg.",
    "Sola står for lavt, ser ingenting.",
    "Det er for kaldt for krigføring i dag."
];

// Logg status
console.log(`Lastet inn ${militaryExcuses.length} unnskyldninger i minnet.`);
console.log("excuses.js ferdig lastet.");

/* Version: #5 */
